/**
 * CrowdStrike Falcon Log Field Knowledge Base
 * Comprehensive definitions for CrowdStrike Falcon logs (Streaming API / FDR)
 * Categories: timestamp, source, destination, action, policy, protocol, traffic, security, default
 */

export default {
    // ============================================================
    //  CORE IDENTIFIERS & METADATA
    // ============================================================
    aid: {
        description: 'Agent ID (Sensor ID) - Unique identifier for the CrowdStrike Falcon sensor installed on the endpoint',
        category: 'source',
        examples: ['0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d']
    },
    SensorId: {
        description: 'Sensor ID (Agent ID) - Unique identifier for the CrowdStrike Falcon sensor (alias for aid)',
        category: 'source',
        examples: ['0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d']
    },
    aip: {
        description: 'Agent IP Address - The external IP address of the sensor as seen by the CrowdStrike cloud',
        category: 'source',
        examples: ['203.0.113.42', '198.51.100.22']
    },
    ComputerName: {
        description: 'Hostname of the endpoint where the event occurred',
        category: 'source',
        examples: ['DESKTOP-ABC123', 'SRV-FILE-01', 'laptop-jsmith']
    },
    cid: {
        description: 'Customer ID - Unique identifier for the CrowdStrike tenant/customer account',
        category: 'default',
        examples: ['1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D-01']
    },
    EventName: {
        description: 'The specific name of the event type generated by the sensor (e.g., ProcessRollup2, NetworkConnectIP4)',
        category: 'action',
        examples: ['ProcessRollup2', 'NetworkConnectIP4', 'DnsRequest', 'UserLogon']
    },
    EventType: {
        description: 'Broad category or exact type string defining the event',
        category: 'action',
        examples: ['DetectionSummaryEvent', 'IncidentSummaryEvent']
    },
    timestamp: {
        description: 'Epoch timestamp of when the event occurred (often in milliseconds)',
        category: 'timestamp',
        examples: ['1706540000000', '1683949210000']
    },
    event_timestamp: {
        description: 'ISO-8601 formatted timestamp of the event',
        category: 'timestamp',
        examples: ['2026-03-07T14:30:00Z']
    },

    // ============================================================
    //  USER & IDENTITY
    // ============================================================
    UserName: {
        description: 'Name of the user account associated with the event/process',
        category: 'source',
        examples: ['jsmith', 'SYSTEM', 'Administrator']
    },
    UserSid: {
        description: 'Security Identifier (SID) of the user account',
        category: 'source',
        examples: ['S-1-5-18', 'S-1-5-21-3623811015-3361044348-30300820-1013']
    },
    UserDomain: {
        description: 'Domain name associated with the user account',
        category: 'source',
        examples: ['CONTOSO', 'NT AUTHORITY']
    },
    LogonType: {
        description: 'Type of logon session (e.g., Interactive, Network, Batch, Service)',
        category: 'action',
        examples: ['2 (Interactive)', '3 (Network)', '10 (RemoteInteractive)']
    },
    LogonTime: {
        description: 'Timestamp when the logon session started',
        category: 'timestamp',
        examples: ['1706540000000']
    },

    // ============================================================
    //  PROCESS ACTIVITY
    // ============================================================
    ProcessId: {
        description: 'Operating System Process ID (PID) of the executing process',
        category: 'default',
        examples: ['4096', '1024']
    },
    TargetProcessId: {
        description: 'Process ID (PID) of the target process (e.g., in CrossProcessOpen or CodeInjection events)',
        category: 'destination',
        examples: ['8192']
    },
    ParentProcessId: {
        description: 'OS Process ID (PID) of the parent process that spawned the execution',
        category: 'default',
        examples: ['1024']
    },
    ImageFileName: {
        description: 'Full file path of the executable image for the process',
        category: 'default',
        examples: ['\\Device\\HarddiskVolume1\\Windows\\System32\\cmd.exe', '\\Device\\HarddiskVolume1\\Windows\\explorer.exe']
    },
    ParentImageFileName: {
        description: 'Full file path of the executable image for the parent process',
        category: 'default',
        examples: ['\\Device\\HarddiskVolume1\\Windows\\System32\\cmd.exe']
    },
    CommandLine: {
        description: 'Command line string used to launch the process, including arguments',
        category: 'action',
        examples: ['"C:\\Windows\\System32\\cmd.exe" /c echo hello', 'powershell.exe -ExecutionPolicy Bypass -File script.ps1']
    },
    ParentCommandLine: {
        description: 'Command line string used to launch the parent process',
        category: 'action',
        examples: ['"C:\\Windows\\explorer.exe"']
    },
    ProcessStartTime: {
        description: 'Epoch timestamp when the process started execution',
        category: 'timestamp',
        examples: ['1706540000000']
    },
    ProcessEndTime: {
        description: 'Epoch timestamp when the process terminated',
        category: 'timestamp',
        examples: ['1706540050000']
    },
    IntegrityLevel: {
        description: 'Windows integrity level under which the process is running (e.g., System, High, Medium, Low)',
        category: 'security',
        examples: ['4096 (System)', '12288 (High)', '8192 (Medium)', '4096 (Low)']
    },
    MD5String: {
        description: 'MD5 hash of the process image file',
        category: 'security',
        examples: ['d41d8cd98f00b204e9800998ecf8427e']
    },
    SHA256String: {
        description: 'SHA-256 hash of the process image file',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    FileHash: {
        description: 'Generic file hash associated with the event (can be MD5, SHA256)',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    SourceProcessId: {
        description: 'Process ID (PID) of the source process performing an action on a target',
        category: 'source',
        examples: ['4096']
    },

    // ============================================================
    //  NETWORK ACTIVITY
    // ============================================================
    LocalAddressIP4: {
        description: 'Local endpoint IPv4 address involved in the network connection',
        category: 'source',
        examples: ['192.168.1.50', '10.0.0.5']
    },
    RemoteAddressIP4: {
        description: 'Remote destination IPv4 address for the network connection',
        category: 'destination',
        examples: ['8.8.8.8', '203.0.113.100']
    },
    LocalAddressIP6: {
        description: 'Local endpoint IPv6 address involved in the network connection',
        category: 'source',
        examples: ['fe80::1ff:fe23:4567:890a']
    },
    RemoteAddressIP6: {
        description: 'Remote destination IPv6 address for the network connection',
        category: 'destination',
        examples: ['2001:4860:4860::8888']
    },
    LocalPort: {
        description: 'Local port number used for the network connection',
        category: 'source',
        examples: ['49152', '54321']
    },
    RemotePort: {
        description: 'Remote port number used for the network connection (e.g., 80, 443)',
        category: 'destination',
        examples: ['80', '443', '53', '3389']
    },
    Protocol: {
        description: 'Network protocol identifier (e.g., 6 for TCP, 17 for UDP)',
        category: 'protocol',
        examples: ['6', '17', '1']
    },
    NetworkProtocol: {
        description: 'Network protocol name (TCP/UDP)',
        category: 'protocol',
        examples: ['TCP', 'UDP', 'ICMP']
    },
    ConnectionDirection: {
        description: 'Direction of the network connection (0=Inbound, 1=Outbound)',
        category: 'traffic',
        examples: ['0', '1']
    },
    DomainName: {
        description: 'Domain name queried in DNS requests or connected to',
        category: 'destination',
        examples: ['google.com', 'malicious.example.com']
    },
    DnsQueryType: {
        description: 'Type of DNS record requested (e.g., 1=A, 28=AAAA)',
        category: 'protocol',
        examples: ['1', '28', '15']
    },

    // ============================================================
    //  FILE & REGISTRY ACTIVITY
    // ============================================================
    TargetFileName: {
        description: 'Full path of the file being created, modified, or deleted',
        category: 'destination',
        examples: ['\\Device\\HarddiskVolume1\\Users\\jsmith\\Downloads\\payload.exe']
    },
    RegistryPath: {
        description: 'Full path of the Windows Registry key being accessed or modified',
        category: 'destination',
        examples: ['\\REGISTRY\\MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run']
    },
    RegistryValueName: {
        description: 'Name of the specific Registry value within the key',
        category: 'destination',
        examples: ['PersistenceKey', 'Backdoor']
    },
    RegistryValueData: {
        description: 'Data written to or read from the Registry value',
        category: 'action',
        examples: ['C:\\Windows\\Temp\\malware.exe']
    },

    // ============================================================
    //  DETECTION & SECURITY (IOA/IOC)
    // ============================================================
    DetectName: {
        description: 'Name of the CrowdStrike detection or Indicator of Attack (IOA)',
        category: 'security',
        examples: ['Suspicious PowerShell Download', 'Credential Dumping', 'Ransomware Activity']
    },
    DetectDescription: {
        description: 'Detailed explanation of why the activity was flagged as a detection',
        category: 'security',
        examples: ['A process attempted to dump LSASS memory which is indicative of credential theft.']
    },
    Severity: {
        description: 'Numeric severity score for the detection (e.g., 10-100)',
        category: 'security',
        examples: ['10', '40', '70', '90']
    },
    SeverityName: {
        description: 'Human-readable severity level (Low, Medium, High, Critical)',
        category: 'security',
        examples: ['Low', 'Medium', 'High', 'Critical']
    },
    Tactic: {
        description: 'MITRE ATT&CK Tactic associated with the detection',
        category: 'security',
        examples: ['DefenseEvasion', 'CredentialAccess', 'Execution']
    },
    Technique: {
        description: 'MITRE ATT&CK Technique associated with the detection',
        category: 'security',
        examples: ['T1059.001', 'T1003.001']
    },
    Objective: {
        description: 'High-level objective or phase of the attack (e.g., Lateral Movement)',
        category: 'security',
        examples: ['Lateral Movement', 'Persistence']
    },
    PatternDispositionDescription: {
        description: 'Action taken by the Falcon sensor (e.g., Detect Only, Blocked, Killed)',
        category: 'action',
        examples: ['Detect Only', 'Process Blocked', 'Process Killed']
    },
    Action: {
        description: 'Specific action performed or mitigated by the sensor',
        category: 'action',
        examples: ['Block', 'Kill', 'Quarantine']
    },
    IocType: {
        description: 'Type of Indicator of Compromise matched (e.g., hash, domain, ipv4)',
        category: 'security',
        examples: ['hash_md5', 'domain', 'ipv4']
    },
    IocValue: {
        description: 'The specific value of the breached Indicator of Compromise',
        category: 'security',
        examples: ['d41d8cd98f00b204e9800998ecf8427e', 'malicious.com']
    },

    // ============================================================
    //  SENSOR & SYSTEM HEALTH
    // ============================================================
    MachineDomain: {
        description: 'Active Directory domain that the endpoint is joined to',
        category: 'source',
        examples: ['CONTOSO.LOCAL']
    },
    OSVersion: {
        description: 'Operating System version of the endpoint',
        category: 'default',
        examples: ['10.0.19045', '14.3.1']
    },
    SensorVersion: {
        description: 'Version of the CrowdStrike Falcon sensor installed',
        category: 'default',
        examples: ['6.58.17208.0']
    },
    PlatformName: {
        description: 'OS platform name of the endpoint (Windows, Mac, Linux)',
        category: 'default',
        examples: ['Windows', 'Mac', 'Linux']
    }
};
