/**
 * Broadcom/Symantec Endpoint Protection (SEP) Log Field Knowledge Base
 * Comprehensive definitions for Symantec Endpoint Protection and EDR logs (JSON/CEF Export)
 * Covers Threat, Traffic, System, Proactive Threat Protection (SONAR), and Application Control events.
 */

export default {
    // ============================================================
    //  CORE IDENTIFIERS & METADATA
    // ============================================================
    Event_Time: {
        description: 'Timestamp when the event occurred on the managed endpoint',
        category: 'timestamp',
        examples: ['2026-03-07T14:30:00Z', '2026-03-07 14:30:00']
    },
    Event_Insert_Time: {
        description: 'Timestamp when the record was inserted into the Symantec Endpoint Protection Manager (SEPM) database',
        category: 'timestamp',
        examples: ['2026-03-07T14:30:15Z']
    },
    Event_ID: {
        description: 'Unique identifier for the specific event record',
        category: 'default',
        examples: ['1234567890ABCDEF']
    },
    Event_Type: {
        description: 'High-level category of the log type (e.g., Traffic, Behavior, Security, Scan, System)',
        category: 'action',
        examples: ['Traffic', 'Behavior', 'Security', 'Scan', 'System']
    },
    Event_Desc: {
        description: 'Textual description summarizing the event or the rule that triggered it',
        category: 'default',
        examples: ['Blocked by Firewall Rule', 'Auto-Protect detected a threat']
    },
    Log_Type: {
        description: 'Type of log generated by SEP (e.g., Risk, Traffic, System, Security)',
        category: 'action',
        examples: ['Risk', 'Traffic', 'System', 'Security']
    },
    Severity: {
        description: 'Assigned severity level reflecting the danger of the event (e.g., Info, Warning, Minor, Major, Critical)',
        category: 'security',
        examples: ['Info', 'Warning', 'Minor', 'Major', 'Critical']
    },
    Severity_Level: {
        description: 'Numeric severity level (1-5) matching the named severity classification',
        category: 'security',
        examples: ['0 (Information)', '3 (Minor)', '5 (Critical)']
    },
    Action: {
        description: 'Action taken by the SEP client in response to the event (e.g., Blocked, Allowed, Quarantined, Deleted)',
        category: 'action',
        examples: ['Blocked', 'Allowed', 'Quarantined', 'Deleted', 'Cleaned']
    },
    Actual_Action: {
        description: 'The final outcome action actually taken if the primary action failed',
        category: 'action',
        examples: ['Left Alone (Failed to Clean)', 'Quarantined']
    },

    // ============================================================
    //  ENDPOINT & SENSOR METADATA
    // ============================================================
    Host_Name: {
        description: 'Hostname of the endpoint where the Symantec agent generated the event',
        category: 'source',
        examples: ['DESKTOP-ABC123', 'SRV-SQL-01']
    },
    Computer_Name: {
        description: 'NetBIOS or associated Windows Computer Name for the endpoint',
        category: 'source',
        examples: ['DESKTOP-ABC123']
    },
    Local_Host_IP: {
        description: 'Primary IP address bound to the local managed endpoint',
        category: 'source',
        examples: ['192.168.1.50', '10.0.0.5']
    },
    Local_Host_MAC: {
        description: 'MAC address of the local endpoint\'s primary network interface',
        category: 'source',
        examples: ['00-1A-2B-3C-4D-5E']
    },
    OS_Name: {
        description: 'Operating system platform of the endpoint',
        category: 'source',
        examples: ['Windows 10', 'macOS 14']
    },
    OS_Version: {
        description: 'Specific version or build string of the endpoint operating system',
        category: 'source',
        examples: ['10.0.19045']
    },

    // ============================================================
    //  SEPM MANAGEMENT METADATA
    // ============================================================
    Domain_Name: {
        description: 'Name of the logical Symantec Endpoint Protection Manager (SEPM) Domain managing the client',
        category: 'source',
        examples: ['Default', 'Finance_Domain']
    },
    Site_Name: {
        description: 'Name of the SEPM Site managing the respective endpoint',
        category: 'source',
        examples: ['Primary_Site']
    },
    Server_Name: {
        description: 'Hostname of the Symantec Endpoint Protection Manager (SEPM) Server processing the log',
        category: 'source',
        examples: ['SEPM-SERVER-01']
    },
    Group_Name: {
        description: 'Symantec policy management group to which the client endpoint belongs',
        category: 'default',
        examples: ['My Company\\Workstations\\Laptops']
    },

    // ============================================================
    //  USER & IDENTITY METADATA
    // ============================================================
    User_Name: {
        description: 'Target user account active on the endpoint during the recorded event',
        category: 'source',
        examples: ['jsmith', 'SYSTEM']
    },
    User_Domain: {
        description: 'Active Directory domain or workgroup associated with the user account',
        category: 'source',
        examples: ['CONTOSO', 'WORKGROUP']
    },

    // ============================================================
    //  PROCESS & APPLICATION ACTIVITY (SONAR / App Control)
    // ============================================================
    Application_Name: {
        description: 'Name of the executable or application related to the event (Target or Originator)',
        category: 'destination',
        examples: ['powershell.exe', 'chrome.exe', 'malware.exe']
    },
    Application_Path: {
        description: 'Full file path mapping to the executable image of the application',
        category: 'destination',
        examples: ['C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe']
    },
    Caller_Process_Name: {
        description: 'Name of the immediate parent or calling process that initiated the action',
        category: 'source',
        examples: ['cmd.exe', 'explorer.exe']
    },
    Caller_Process_Path: {
        description: 'Full file path to the executable image of the parent/calling process',
        category: 'source',
        examples: ['C:\\Windows\\System32\\cmd.exe']
    },
    Process_ID: {
        description: 'Operating System Process ID (PID) of the primary executing process',
        category: 'destination',
        examples: ['8192']
    },
    PIDs: {
        description: 'Array or string of associated Process IDs',
        category: 'destination',
        examples: ['8192, 1024']
    },
    Parent_Process_ID: {
        description: 'Process ID (PID) of the immediate calling or parent process',
        category: 'source',
        examples: ['1024']
    },

    // ============================================================
    //  FILE ACTIVITY & HASHES
    // ============================================================
    File_Path: {
        description: 'Full file path of a file that was detected, quarantined, or modified',
        category: 'destination',
        examples: ['C:\\Users\\jsmith\\Downloads\\payload.exe']
    },
    File_Name: {
        description: 'Name of the file targeted by the event action or detection',
        category: 'destination',
        examples: ['payload.exe', 'document.docx']
    },
    File_Size: {
        description: 'Size of the targeted file object on disk (in bytes)',
        category: 'default',
        examples: ['1048576']
    },
    Hash_Type: {
        description: 'Type of hash algorithm used for the accompanying Hash value',
        category: 'security',
        examples: ['SHA-256', 'MD5']
    },
    Hash: {
        description: 'Cryptographic hash value of the corresponding file or application',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    SHA256: {
        description: 'Explicit SHA-256 hash of the File/Application payload',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    MD5: {
        description: 'Explicit MD5 hash of the File/Application payload',
        category: 'security',
        examples: ['d41d8cd98f00b204e9800998ecf8427e']
    },

    // ============================================================
    //  NETWORK & FIREWALL ACTIVITY (Traffic)
    // ============================================================
    Local_IP: {
        description: 'Local Source/Destination IPv4 or IPv6 address bound to the endpoint',
        category: 'source',
        examples: ['192.168.1.50']
    },
    Local_Port: {
        description: 'Local port mapped to the network socket',
        category: 'source',
        examples: ['54321']
    },
    Remote_IP: {
        description: 'Remote Source/Destination IPv4 or IPv6 address',
        category: 'destination',
        examples: ['203.0.113.100']
    },
    Remote_Port: {
        description: 'Remote port (e.g., 80, 443, 53) involved in the network session',
        category: 'destination',
        examples: ['443']
    },
    Protocol: {
        description: 'Layer 4 Transport Protocol or numeric protocol ID (e.g., TCP, UDP, ICMP, 6, 17)',
        category: 'protocol',
        examples: ['TCP', 'UDP', 'ICMP', '6', '17']
    },
    Direction: {
        description: 'Network communication connection direction (Outbound vs Inbound)',
        category: 'traffic',
        examples: ['Outbound', 'Inbound', 'Incoming', 'Outgoing']
    },
    Traffic_Direction: {
        description: 'Alternate identifier for Network communication direction',
        category: 'traffic',
        examples: ['0 (Inbound)', '1 (Outbound)']
    },
    Remote_Host_Name: {
        description: 'Resolved hostname or FQDN of the remote IP address',
        category: 'destination',
        examples: ['api.example.com', 'malicious.com']
    },
    Network_Protocol: {
        description: 'Application Layer Protocol associated with the firewall trace',
        category: 'protocol',
        examples: ['HTTP', 'HTTPS', 'DNS']
    },

    // ============================================================
    //  SECURITY DETECTIONS, IPS & ANTIMALWARE
    // ============================================================
    Risk_Name: {
        description: 'Name or classification defining the detected static or behavioral virus/Spyware threat',
        category: 'security',
        examples: ['W32.WannaCry', 'Trojan.Gen.SMH']
    },
    Risk_Type: {
        description: 'Category of the threat detected (e.g., Virus, heuristic, SecurityRisk, Spyware)',
        category: 'security',
        examples: ['Virus', 'Heuristic', 'SecurityRisk', 'Spyware']
    },
    Rule_Name: {
        description: 'Name of the firewall, application control, or SONAR rule triggering the event',
        category: 'security',
        examples: ['Block all outgoing FTP to the Internet', 'Suspicious script execution']
    },
    Category_Type: {
        description: 'Categorical type of the Intrusion Prevention (IPS) or SONAR alert',
        category: 'security',
        examples: ['Intrusion Prevention', 'SONAR']
    },
    Category_Description: {
        description: 'Specific IPS signature or SONAR behavioral heuristic description',
        category: 'security',
        examples: ['System Infected: Trojan.Gen Activity']
    },
    Intrusion_URL: {
        description: 'Target Uniform Resource Locator (URL) requested in IPS Network web traffic events',
        category: 'destination',
        examples: ['http://malicious.example.com/payload.exe']
    },
    Intrusion_Payload_URL: {
        description: 'URL representing where the malicious payload was requested from',
        category: 'destination',
        examples: ['http://malicious.example.com/payload.exe']
    },
    Detection_Score: {
        description: 'SONAR or Advanced Machine Learning score representing the confidence of the conviction',
        category: 'security',
        examples: ['98', '100']
    },
    Sub_Action: {
        description: 'Detailed secondary action taken alongside the primary security Action',
        category: 'action',
        examples: ['Process Terminated', 'File Deleted']
    }
};
