/**
 * Trend Micro Endpoint Log Field Knowledge Base
 * Comprehensive definitions for Trend Micro Vision One / Apex One Endpoint logs (XDR JSON Export)
 * Covers Process, Network, File, Registry, Identity, and Alert schemas
 */

export default {
    // ============================================================
    //  CORE IDENTIFIERS & METADATA
    // ============================================================
    uuid: {
        description: 'Unique global identifier for the specific event record within Vision One',
        category: 'default',
        examples: ['12345678-ABCD-9012-3456-7890ABCDEF12']
    },
    logId: {
        description: 'Unique identifier for the specific log entry generated by the endpoint sensor',
        category: 'default',
        examples: ['L-123456789']
    },
    eventTime: {
        description: 'Unix timestamp indicating the precise time the event occurred on the endpoint',
        category: 'timestamp',
        examples: ['1706540000000']
    },
    eventTimeDT: {
        description: 'ISO-8601 formatted timestamp of the event occurrence',
        category: 'timestamp',
        examples: ['2026-03-07T14:30:00.0000000Z']
    },
    logGenerationTime: {
        description: 'Timestamp when the log was generated or ingested into the Vision One data lake',
        category: 'timestamp',
        examples: ['2026-03-07T14:30:15.123Z']
    },
    logType: {
        description: 'High-level categorization of the event telemetry (e.g., PROCESS, NETWORK, FILE)',
        category: 'action',
        examples: ['PROCESS', 'NETWORK', 'FILE', 'REGISTRY_KEY', 'USER_ACTIVITY']
    },
    eventSubId: {
        description: 'Detailed sub-categorization ID defining the exact action of the event type',
        category: 'action',
        examples: ['1 (Process Launch)', '2 (Process Terminate)', '10 (File Create)']
    },
    logStatus: {
        description: 'Current processing status of the log record within Trend Micro',
        category: 'default',
        examples: ['Normal', 'Delayed']
    },
    productCode: {
        description: 'Identifier for the specific Trend Micro product that generated the event (e.g., Apex One, Vision One Sensor)',
        category: 'source',
        examples: ['sao (Apex One)', 'xdr (Vision One)']
    },
    companyId: {
        description: 'Unique identifier for the corporate tenant/customer account',
        category: 'default',
        examples: ['COMPANY-123456']
    },

    // ============================================================
    //  ENDPOINT & SENSOR METADATA
    // ============================================================
    endpointGuid: {
        description: 'Unique global identifier assigned to the Trend Micro endpoint sensor',
        category: 'source',
        examples: ['A1B2C3D4-E5F6-7890-A1B2-C3D4E5F67890']
    },
    endpointHostName: {
        description: 'Hostname of the endpoint where the event was recorded',
        category: 'source',
        examples: ['DESKTOP-ABC123', 'SRV-SQL-01']
    },
    endpointIp: {
        description: 'Primary IP address bound to the endpoint generating the log',
        category: 'source',
        examples: ['192.168.1.50', '10.0.0.5']
    },
    endpointMacAddress: {
        description: 'MAC address of the endpoint\'s primary network interface',
        category: 'source',
        examples: ['00:1A:2B:3C:4D:5E']
    },
    osName: {
        description: 'Operating system platform of the endpoint (e.g., Windows, macOS, Linux)',
        category: 'source',
        examples: ['Windows', 'macOS', 'Linux']
    },
    osVersion: {
        description: 'Specific version or build string of the endpoint operating system',
        category: 'source',
        examples: ['Windows 10.0.19045', '14.3.1']
    },

    // ============================================================
    //  USER & IDENTITY METADATA
    // ============================================================
    logonUser: {
        description: 'Target user account active on the endpoint during the recorded event',
        category: 'source',
        examples: ['jsmith', 'SYSTEM']
    },
    logonDomain: {
        description: 'Active Directory domain or workgroup associated with the user account',
        category: 'source',
        examples: ['CONTOSO', 'WORKGROUP']
    },
    logonType: {
        description: 'Type of logon session (e.g., Interactive, Network, Unlock) for user activity logs',
        category: 'action',
        examples: ['Interactive', 'Network', 'RemoteInteractive']
    },
    authPackage: {
        description: 'Security package used to authenticate the logon session',
        category: 'security',
        examples: ['Negotiate', 'Kerberos', 'NTLM']
    },
    userLogonId: {
        description: 'Operating System generated Logon ID mapping to the user session',
        category: 'default',
        examples: ['0x1a2b3c']
    },

    // ============================================================
    //  PROCESS ACTIVITY
    // ============================================================
    processName: {
        description: 'Name of the executable file associated with the primary process',
        category: 'destination',
        examples: ['powershell.exe', 'cmd.exe', 'malware.exe']
    },
    processFilePath: {
        description: 'Full file path mapping to the executable image of the primary process',
        category: 'destination',
        examples: ['C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe']
    },
    processCmd: {
        description: 'Full command line arguments mapping to the executing primary process',
        category: 'action',
        examples: ['powershell.exe -ExecutionPolicy Bypass -encodedCommand IAA...']
    },
    processId: {
        description: 'Operating System Process ID (PID) of the primary process',
        category: 'destination',
        examples: ['8192']
    },
    processFileHashSha256: {
        description: 'SHA-256 hash belonging to the primary process executable',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    processFileHashSha1: {
        description: 'SHA-1 hash belonging to the primary process executable',
        category: 'security',
        examples: ['da39a3ee5e6b4b0d3255bfef95601890afd80709']
    },
    processFileHashMd5: {
        description: 'MD5 hash belonging to the primary process executable',
        category: 'security',
        examples: ['d41d8cd98f00b204e9800998ecf8427e']
    },

    // ============================================================
    //  PARENT PROCESS
    // ============================================================
    parentProcessName: {
        description: 'Name of the immediate parent process that spawned the primary process execution',
        category: 'source',
        examples: ['explorer.exe', 'cmd.exe']
    },
    parentProcessFilePath: {
        description: 'Full file path to the executable image of the parent process',
        category: 'source',
        examples: ['C:\\Windows\\explorer.exe']
    },
    parentProcessCmd: {
        description: 'Command line string used to originally launch the parent process (including arguments)',
        category: 'action',
        examples: ['cmd.exe /c start script.bat']
    },
    parentProcessId: {
        description: 'Process ID (PID) of the immediate parent process',
        category: 'source',
        examples: ['1024']
    },
    parentProcessFileHashSha256: {
        description: 'SHA-256 hash of the parent process executable payload',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },

    // ============================================================
    //  FILE ACTIVITY
    // ============================================================
    objectFilePath: {
        description: 'Full file path of a file that was created, read, modified, or deleted',
        category: 'destination',
        examples: ['C:\\Users\\jsmith\\Downloads\\payload.exe']
    },
    objectFileName: {
        description: 'Name of the file targeted by the event action',
        category: 'destination',
        examples: ['payload.exe', 'document.docx']
    },
    objectFileExtension: {
        description: 'Extension parsed from the target file name',
        category: 'default',
        examples: ['exe', 'dll', 'docx']
    },
    objectFileSize: {
        description: 'Size of the targeted file object on disk (in bytes)',
        category: 'default',
        examples: ['1048576']
    },
    objectFileHashSha256: {
        description: 'SHA-256 hash of the targeted file data',
        category: 'security',
        examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']
    },
    objectFileHashSha1: {
        description: 'SHA-1 hash of the targeted file data',
        category: 'security',
        examples: ['da39a3ee5e6b4b0d3255bfef95601890afd80709']
    },
    objectFileHashMd5: {
        description: 'MD5 hash of the targeted file data',
        category: 'security',
        examples: ['d41d8cd98f00b204e9800998ecf8427e']
    },

    // ============================================================
    //  NETWORK ACTIVITY
    // ============================================================
    srcIp: {
        description: 'Local Source IPv4 or IPv6 address initiating or receiving the connection',
        category: 'source',
        examples: ['192.168.1.50']
    },
    srcPort: {
        description: 'Local Source port mapped to the network socket',
        category: 'source',
        examples: ['54321']
    },
    dstIp: {
        description: 'Remote Destination IPv4 or IPv6 address',
        category: 'destination',
        examples: ['203.0.113.100']
    },
    dstPort: {
        description: 'Remote Destination port (e.g., 80, 443, 53)',
        category: 'destination',
        examples: ['443']
    },
    protocol: {
        description: 'Layer 4 Transport Protocol (e.g., TCP, UDP, ICMP)',
        category: 'protocol',
        examples: ['TCP', 'UDP']
    },
    connectionDirection: {
        description: 'Network communication connection direction (Outbound vs Inbound)',
        category: 'traffic',
        examples: ['Outbound', 'Inbound']
    },
    requestUrl: {
        description: 'Target Uniform Resource Locator (URL) requested in web traffic events',
        category: 'destination',
        examples: ['http://malicious.example.com/payload.exe']
    },
    requestDomain: {
        description: 'Destination domain or FQDN associated with the network web request',
        category: 'destination',
        examples: ['api.example.com', 'malicious.com']
    },
    referrer: {
        description: 'HTTP Referer string indicating the originating web page',
        category: 'source',
        examples: ['https://search.example.com/']
    },
    userAgent: {
        description: 'HTTP Client User-Agent string utilized during the request',
        category: 'source',
        examples: ['Mozilla/5.0 (Windows NT 10.0; Win64; x64)']
    },

    // ============================================================
    //  REGISTRY ACTIVITY
    // ============================================================
    registryKey: {
        description: 'Full hierarchy path to the Windows Registry Key being modified or accessed',
        category: 'destination',
        examples: ['HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run']
    },
    registryValueName: {
        description: 'Name of the specific Registry value within the targeted key',
        category: 'destination',
        examples: ['PersistenceKey']
    },
    registryValueData: {
        description: 'Data written into the targeted Windows Registry mapping',
        category: 'action',
        examples: ['C:\\Windows\\Temp\\malware.exe']
    },

    // ============================================================
    //  INCIDENTS, ALERTS & DETECTIONS
    // ============================================================
    action: {
        description: 'Primary security action evaluated or triggered (e.g., Block, Monitor, Quarantine)',
        category: 'action',
        examples: ['Block', 'Quarantine', 'Monitor', 'Clean']
    },
    actionResult: {
        description: 'Result of the deployed security action (e.g., Success, Failed)',
        category: 'action',
        examples: ['Success', 'Failed']
    },
    threatName: {
        description: 'Name or classification defining the detected static or behavioral threat',
        category: 'security',
        examples: ['Ransom.Win32.WannaCry', 'TROJ_GENERIC']
    },
    threatType: {
        description: 'Category of the threat detected (e.g., Malware, Spyware, Behavioral)',
        category: 'security',
        examples: ['Malware', 'Spyware', 'Behavioral']
    },
    riskLevel: {
        description: 'Assigned risk or severity level reflecting the danger of the threat (Low, Medium, High, Critical)',
        category: 'security',
        examples: ['High', 'Critical', 'Medium', 'Low']
    },
    ruleId: {
        description: 'Identifier mapped to the detection rule or analytic producing the alert',
        category: 'security',
        examples: ['RULE-100456']
    },
    filterAction: {
        description: 'Action taken by the sensor filter driver on the event (e.g., Passed, Dropped)',
        category: 'security',
        examples: ['Passed', 'Dropped', 'Blocked']
    }
};
